export const questions = [
  {
    question: "Which of the following hormones is a steroid?",
    answer: " Estrogen",
    optionOne: "Estrogen",
    optionTwo: "Glucagon",
    optionThree: "Insulin",
    optionFour: "Oxytocin",
  },
  {
    question: " Which one of the following is not a function of the liver?",
    answer: " Reproduction",
    optionOne: " Regulation of blood sugar",
    optionTwo: "Enzyme activation",
    optionThree: "Detoxification",
    optionFour: "Reproduction",
  },
  {
    question:
      "  Which of the following is a large blood vessel that carries blood away from the heart?",
    answer: " Artrey",
    optionOne: " Vein",
    optionTwo: "Artery",
    optionThree: "Capillary",
    optionFour: "Nerver",
  },
  {
    question: "  What percentage of the human body is water?",
    answer: " 66%",
    optionOne: " 70%",
    optionTwo: "80%",
    optionThree: "40%",
    optionFour: "66%",
  },
  {
    question: " 13 - Chambered heart occurs in ",
    answer: " Cockroach",
    optionOne: " Leech",
    optionTwo: "Snail",
    optionThree: "Earthworm",
    optionFour: "Cockroach",
  },
  {
    question: "Hardest Part of the Human Body? ",
    answer: "  Tooth Enamel",
    optionOne: "  Tooth Enamel",
    optionTwo: "Femur",
    optionThree: "Temporal bone of skull",
    optionFour: "Knee bone",
  },
  {
    question: "	What is the speed that a human brain sends message? ",
    answer: "240mph ",
    optionOne: "100mph ",
    optionTwo: "140mph",
    optionThree: "200mph",
    optionFour: "240mph",
  },
  {
    question:
      "Which of the following organs of human body provide instant energy? ",
    answer: "Liver ",
    optionOne: "Lungs ",
    optionTwo: "Liver",
    optionThree: "Pancreas",
    optionFour: "Muscles",
  },
  {
    question:
      "The vitamin which is very liable and easily destroyed during cooking as well as storage is",
    answer: "Vitamin C ",
    optionOne: "Vitamin A ",
    optionTwo: "Vitamin B6",
    optionThree: "Vitamin C",
    optionFour: "Vitamin K",
  },
  {
    question: " Which organ of the body produces the fluid known as bile?",
    answer: "Liver",
    optionOne: "Liver ",
    optionTwo: "Pancreas",
    optionThree: " Gall bladder",
    optionFour: "  Kidney",
  },
  {
    question: "What is Coronavirus?",
    answer: "Both A and B are correct",
    optionOne: " It is a large family of viruses. ",
    optionTwo: "It belongs to the family of Nidovirus.",
    optionThree: " Both A and B are correct",
    optionFour: "Only A is correct. ",
  },
  {
    question:
      "Thailand announced that it has proceeded to test its novel coronavirus vaccine on which animal/bird?",
    answer: "Monkeys",
    optionOne: "Kites ",
    optionTwo: "Monkeys",
    optionThree: " Lizards",
    optionFour: " Hens",
  },
  {
    question: "The first case of novel coronavirus was identified in .....",
    answer: "Wuhan, Hubei ",
    optionOne: "Beijing ",
    optionTwo: " Shanghai",
    optionThree: " Wuhan, Hubei ",
    optionFour: " Tianjin ",
  },
  {
    question:
      "In India, when did the second phase of COVID-19 vaccination start?",
    answer: "March 2021",
    optionOne: "February 2021 ",
    optionTwo: " December 2020",
    optionThree: "March 2021 ",
    optionFour: "January 2021 ",
  },
];
